#!/usr/bin/env python3
import json
import re
from typing import Iterator, List, NamedTuple, Optional

import pandas as pd
from dateutil.parser import parse as parse_date

date_pattern = re.compile(r'^(?:([0-9]{2})/)?(?:([0-9]{2})/)?([0-9]{4})$')


class Book(NamedTuple):
    title: str
    authors: List[str]
    genres: List[str]
    publication_date: Optional[str]
    publication_year: Optional[int]
    editor: str
    pages: int
    isbn: str
    read: bool
    summary: str


def parse_book(book: pd.Series) -> dict:
    publication = book['Date de publication']
    publication_date = None
    publication_year = None
    if publication:
        try:
            publication_year = int(publication)
        except ValueError:
            publication_dt = parse_date(publication)
            publication_date = publication_dt.date().isoformat()
            publication_year = publication_dt.year
    return Book(
        title=book['Titre'],
        authors=book['Auteurs'].split(', '),
        genres=book['Genres'].split(', '),
        publication_date=publication_date,
        publication_year=publication_year,
        editor=book['Editeur'],
        pages=book['Pages'],
        isbn=book['ISBN'],
        read=book['Lu'] == 'Oui',
        summary=book['Résumé'],
    )._asdict()


def parse_books(books: pd.DataFrame) -> Iterator[dict]:
    for _, book in books.iterrows():
        yield parse_book(book)


df = pd.read_excel('MaBibliotheque.xls', na_filter=False)
books = list(parse_books(df))
print(json.dumps(books))
