[project]
name = "mybooks"
version = "0.1.0"
description = "Generate an interactie list of books from MyLibrary export"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pandas>=2.2.3",
    "xlrd>=2.0.1",
]
